const PDFDocument = require('pdfkit');
const Product = require('../models/Product');

const generateBOMPDF = async (req, res) => {
  try {
    const product = await Product.findById(req.params.id)
      .populate('components')
      .populate('createdBy', 'name');

    if (!product) {
      return res.status(404).send('Product not found');
    }

    const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="BOM-${product.name}-v${product.version}.pdf"`);
    doc.pipe(res);

    // 1. HEADER
    doc.font('Helvetica-Bold').fontSize(20).fillColor('#1a1a2e').text('VaultCore PDM', { continued: true });
    doc.font('Helvetica').fontSize(14).fillColor('#666666').text('   Bill of Materials Report', { baseline: 'bottom' });
    
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(0.5);
    
    doc.fontSize(9).fillColor('#999999').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, { align: 'right' });
    doc.moveDown(1);

    // 2. PRODUCT INFO
    const startY = doc.y;
    doc.fontSize(10).fillColor('#333333');
    doc.font('Helvetica-Bold').text('Product Name: ', 50, startY, { continued: true }).font('Helvetica').text(product.name);
    doc.font('Helvetica-Bold').text('Version: ', 50, startY + 15, { continued: true }).font('Helvetica').text(product.version);
    doc.font('Helvetica-Bold').text('Category: ', 50, startY + 30, { continued: true }).font('Helvetica').text(product.category);

    doc.font('Helvetica-Bold').text('Status: ', 300, startY, { continued: true }).font('Helvetica').text(product.status);
    doc.font('Helvetica-Bold').text('Created By: ', 300, startY + 15, { continued: true }).font('Helvetica').text(product.createdBy ? product.createdBy.name : 'Unknown');
    doc.font('Helvetica-Bold').text('Total Parts: ', 300, startY + 30, { continued: true }).font('Helvetica').text(product.components.length.toString());

    doc.y = startY + 50;

    // 3. DESCRIPTION
    if (product.description) {
      doc.moveDown(0.5);
      doc.font('Helvetica-Bold').text('Description:');
      doc.font('Helvetica').text(product.description, { width: 495 });
      doc.moveDown(1);
    } else {
      doc.moveDown(1);
    }

    // 4. BOM TABLE
    const tableTop = doc.y;
    doc.rect(50, tableTop, 495, 22).fill('#1a1a2e');
    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(9);
    
    const colX = {
      index: 55,
      part: 80,
      name: 145,
      qty: 255,
      unit: 290,
      material: 330,
      spec: 400
    };

    doc.text('#', colX.index, tableTop + 6);
    doc.text('Part No.', colX.part, tableTop + 6);
    doc.text('Name', colX.name, tableTop + 6);
    doc.text('Qty', colX.qty, tableTop + 6);
    doc.text('Unit', colX.unit, tableTop + 6);
    doc.text('Material', colX.material, tableTop + 6);
    doc.text('Specifications', colX.spec, tableTop + 6);

    let y = tableTop + 22;
    doc.font('Helvetica').fontSize(8.5);

    product.components.forEach((comp, index) => {
      if (y > 750) {
        doc.addPage();
        y = 50;
      }

      if (index % 2 === 0) {
        doc.rect(50, y, 495, 22).fill('#f8f9fa');
      }

      doc.fillColor('#333333');
      doc.text((index + 1).toString(), colX.index, y + 6);
      doc.text(comp.partNumber || '-', colX.part, y + 6, { width: 60, height: 12, lineBreak: false });
      doc.text(comp.name, colX.name, y + 6, { width: 105, height: 12, lineBreak: false });
      doc.text(comp.quantity.toString(), colX.qty, y + 6);
      doc.text(comp.unit, colX.unit, y + 6);
      doc.text(comp.material || '-', colX.material, y + 6, { width: 65, height: 12, lineBreak: false });
      doc.text(comp.specifications || '-', colX.spec, y + 6, { width: 140, height: 12, lineBreak: false });

      y += 22;
    });

    // 5. FOOTER
    // Add page numbers
    const range = doc.bufferedPageRange();
    for (let i = range.start, end = range.start + range.count, pageIndex = 1; i < end; i++, pageIndex++) {
      doc.switchToPage(i);
      
      const footerY = 800; // near bottom of A4
      doc.moveTo(50, footerY).lineTo(545, footerY).strokeColor('#cccccc').stroke();
      
      doc.fontSize(8).fillColor('#999999');
      doc.text('Generated by VaultCore PDM System', 50, footerY + 10, { align: 'center' });
      doc.text(`Page ${pageIndex} of ${range.count}`, 50, footerY + 10, { align: 'right' });
    }

    doc.end();

  } catch (err) {
    console.error(err);
    res.status(500).send('PDF generation failed');
  }
};

module.exports = {
  generateBOMPDF
};
